### ISSUE TITLE
Equivalent of nom's map_res

### ISSUE THREAD

**Issue by jeanm** [J-F-Liu/pom#1]
[nom](https://github.com/Geal/nom) has a very useful [`map_res`](https://docs.rs/nom/2.0.1/nom/macro.map_res.html) combinator:
> applies a function returning a Result to the output of `IResult`, returns `Done(input, o)` if the result is `Ok(o)`, or `Error(0)`

Something like that would come in handy to get rid of all the `unwrap()`s in places like:

```rust
.map(|bytes|String::from_utf8(bytes).unwrap())
```

(there are a few cases of this in your JSON example code)

**Comment by J-F-Liu** [comment]
Added map_res, this makes the parser code neater.
