### ISSUE TITLE
Cargo build fails with v0.8.1 on crates.io

### ISSUE THREAD

**Issue by alienscience** [J-F-Liu/pom#10]
Hello,
  This github repository compiles fine for me but when I add `pom` as a dependency to my Cargo.toml I get a compiler error on build:

```
~/.../catfood/smtpdr$ (master): cargo build
   Compiling pom v0.8.1
error: unexpected `?`
   --> .../pom-0.8.1/src/parser.rs:192:19
    |
192 | 		  T: Train<I> + ?Sized
    | 		                ^

error: aborting due to previous error

error: Could not compile `pom`.

```
Is the version on crates.io out of date?

**Comment by J-F-Liu** [comment]
v0.8.1 builds on Rust nightly, the next release will support Rust stable.
