### ISSUE TITLE
pest are much faster than POM, is there any chance to catch up?

### ISSUE THREAD

**Issue by lygstate** [J-F-Liu/pom#12]

**Comment by J-F-Liu** [comment]
2.x branch is created with the goal to improve performance.

**Comment by lygstate** [comment]
杭州很近啊，我在南京

**Comment by J-F-Liu** [comment]
2.0.0 alpha was released, it has some performance improvement, but still cannot catch up pest. Hope some others can help. Thanks for your interest to this project, I'll close this issue now.
