### ISSUE TITLE
Compared with nom?

### ISSUE THREAD

**Issue by vincascm** [J-F-Liu/pom#16]
i found a crate, [nom](https://github.com/Geal/nom), compared the two what are the advantages and disadvantages?

**Comment by J-F-Liu** [comment]
Simply,
nom: macro based, less flexible grammar, good performance, hard to debug;
pom: parser combinator, more flexible, good readability, easy to extend;

**Comment by vincascm** [comment]
THX，very nice work.

**Comment by alishir** [comment]
Is there any performance comparison between nom and pom?

**Comment by 0b01** [comment]
@alishir pom should be much much slower(100x) due to allocating and formatting error message everytime a parser doesn't match.
