### ISSUE TITLE
Docs.rs docs are broken

### ISSUE THREAD

**Issue by theduke** [J-F-Liu/pom#18]
https://docs.rs/crate/pom/2.0.0 shows an error: Failed to build crate docs.

**Comment by J-F-Liu** [comment]
No error when build locally. May related to https://github.com/onur/docs.rs/issues/171

**Comment by Flarp** [comment]
@J-F-Liu The issues themselves are not related, but the solutions are.

**Comment by J-F-Liu** [comment]
Related issue is fixed.
