### ISSUE TITLE
Additional context for Parser

### ISSUE THREAD

**Issue by MageSlayer** [J-F-Liu/pom#21]
Hi

Currently, I am trying to choose some parser library.
pom looks nice due to lack of "macros hell" compared to nom.
I guess you feel the same :)

However, I have one requirement which spoils all nice code - I must create parsed values inside special allocator/arena object. Thus I need to be able to access it within each and every function returning Parser struct. I guess it's something Serde calls "stateful serialization".

The easiest way to do that is to embed another generic struct field within Parser which would be accessible everywhere somehow - provide additional Parser reference in all combinators or stuff like that. Currently I see no other way to do that but to fork/branch "pom" and thread additional parameter through each combinator. 

Could you suggest any other way to avoid forking?
BR

**Comment by J-F-Liu** [comment]
You may send a PR or create a parser like [this](https://github.com/J-F-Liu/lopdf/blob/47806f847bfcfb25e68274b3fe6f01db64fd9936/src/parser.rs#L157)

**Comment by MageSlayer** [comment]
Yeap, looks like the idea of wrapping is quite close to what I need.
Thanks a lot.
