### ISSUE TITLE
Issue from "Parser::new" method on current version.

### ISSUE THREAD

**Issue by pictca** [J-F-Liu/pom#35]
In the legendary project [clacks](https://github.com/habnabit/clacks/tree/master/clacks_tl_codegen)  use  `pom =  "1.1.0"`. My current job to merge some legendary code to a new project with current pom version `v 3.0` which changed on core API. I'm stuck on define `new` method on Parser
old but it works well
[source](https://github.com/habnabit/clacks/blob/77d331770e71fddda53785d9a62b63d47125d65d/clacks_tl_codegen/src/lib.rs#L203)
```rust
fn output<T: 'static>(inner: Parser<u8, T>) -> Parser<u8, Matched<T>> {
        Parser::new(move |input| {
            let start = input.position();
            let output = inner.parse(input)?;
            let end = input.position();
            Ok(Matched(output, utf8(input.segment(start, end))))
        })
    }
#[derive(Debug, Clone)]
pub struct Matched<T>(pub T, pub String);
fn utf8(v: Vec<u8>) -> String {
     String::from_utf8(v).unwrap()
}
``` 
How can i apply `Parser::new` with current version?

**Comment by J-F-Liu** [comment]
Try something like:
```rust
Parser::new(move |input: &'a [u8], start: usize| {
    inner.parse(input, start).map(|(_, end)| (&input[start..end], end))
})
```

**Comment by pictca** [comment]
thank you
