### ISSUE TITLE
Nightly only

### ISSUE THREAD

**Issue by jsgf** [J-F-Liu/pom#6]
Hi -

Pom looks very interesting, and I'd love to try it out on my project (parsing lots of ad-hoc mini-grammars in various file formats and protocols), but I'm constrained to stable rustc only.

Do you have an idea of what the stabilization timeline is for the features you're using? Or how hard it would be to make it work in stable?

From a quick look, I found:

- use of `?Sized` where clause doesn't seem to parse on stable (which seems like a bug, because it does within a `<T: ?Sized>`)
- loops with values (trivial to avoid cleanly)
- collections bound (functional change to the API)

**Comment by J-F-Liu** [comment]
Yes, I'd like to have 1.0 release build on stable rust, then create a 2.x branch and move forward.

**Comment by jsgf** [comment]
Fixed
